CREATE DATABASE TouristAgency

CREATE TABLE Countries (
	Id INT PRIMARY KEY IDENTITY,
	[Name] NVARCHAR(50) NOT NULL
)

CREATE TABLE Destinations (
	Id INT PRIMARY KEY IDENTITY,
	[Name] VARCHAR(50) NOT NULL,
	CountryId INT CONSTRAINT FK_CountryId FOREIGN KEY REFERENCES Countries(Id) NOT NULL
)

CREATE TABLE Rooms (
	Id INT PRIMARY KEY IDENTITY,
	[Type] VARCHAR(40) NOT NULL,
	Price DECIMAL (18,2) NOT NULL,
	BedCount INT CONSTRAINT CK_BedCount CHECK (BedCount BETWEEN 1 AND 10) NOT NULL
)

CREATE TABLE Hotels (
	Id INT PRIMARY KEY IDENTITY,
	[Name] VARCHAR(50) NOT NULL,
	DestinationId INT CONSTRAINT FK_DestinationId FOREIGN KEY REFERENCES Destinations (Id) NOT NULL
)

CREATE TABLE Tourists (
	Id INT PRIMARY KEY IDENTITY,
	[Name] NVARCHAR(80) NOT NULL,
	PhoneNumber VARCHAR(20) NOT NULL,
	Email VARCHAR(80),
	CountryId INT CONSTRAINT FK_CountryId_Tourists FOREIGN KEY REFERENCES Countries (Id) NOT NULL
)

CREATE TABLE Bookings (
	Id INT PRIMARY KEY IDENTITY,
	ArrivalDate DATETIME2 NOT NULL,
	DepartureDate DATETIME2 NOT NULL,
	AdultsCount INT CONSTRAINT CK_AdultsCount CHECK (AdultsCount BETWEEN 1 AND 10) NOT NULL,
	ChildrenCount INT CONSTRAINT CK_ChildrenCount CHECK (ChildrenCount BETWEEN 0 AND 9) NOT NULL,
	TouristId INT CONSTRAINT FK_TouristId_Bookings FOREIGN KEY REFERENCES Tourists (Id) NOT NULL,
	HotelId INT CONSTRAINT FK_HotelId_Bookings FOREIGN KEY REFERENCES Hotels (Id) NOT NULL,
	RoomId INT CONSTRAINT FK_RoomId_Bookings FOREIGN KEY REFERENCES Rooms (Id) NOT NULL
)

CREATE TABLE HotelsRooms (
	HotelId INT CONSTRAINT FK_HotelId_HotelsRooms FOREIGN KEY REFERENCES Hotels (Id),
	RoomId INT CONSTRAINT FK_RoomId_HotelsRooms FOREIGN KEY REFERENCES Rooms (Id),
	PRIMARY KEY (HotelId, RoomId)
)