CREATE DATABASE SoftUni

CREATE TABLE Towns (
	Id INT PRIMARY KEY IDENTITY,
	[Name] NVARCHAR(255) NOT NULL
)

CREATE TABLE Addresses (
	Id INT PRIMARY KEY IDENTITY,
	AddressText NVARCHAR(255) NOT NULL,
	TownId INT CONSTRAINT FK_TownId FOREIGN KEY REFERENCES Towns (Id) NOT NULL
)

CREATE TABLE Departments (
	Id INT PRIMARY KEY IDENTITY,
	[Name] NVARCHAR(255) NOT NULL
)

CREATE TABLE Employees (
	Id INT PRIMARY KEY IDENTITY,
	FirstName NVARCHAR(255) NOT NULL,
	MiddleName NVARCHAR(255) NULL,
	LastName NVARCHAR(255) NOT NULL,
	JobTitle NVARCHAR(255) NOT NULL,
	DepartmentId INT CONSTRAINT FK_DepartmentId FOREIGN KEY REFERENCES Departments(Id) NOT NULL,
	HireDate DATE NOT NULL,
	Salary MONEY NOT NULL,
	AddressId INT CONSTRAINT FK_AddressId FOREIGN KEY REFERENCES Addresses(Id) NULL
)