CREATE DATABASE OnlineStore

CREATE TABLE ItemTypes (
	ItemTypeID INT PRIMARY KEY,
	[Name] NVARCHAR(255) NOT NULL
)

CREATE TABLE Cities (
	CityID INT PRIMARY KEY,
	[Name] NVARCHAR(255) NOT NULL
)

CREATE TABLE Items (
	ItemID INT PRIMARY KEY,
	[Name] NVARCHAR(255) NOT NULL,
	ItemTypeID INT CONSTRAINT FK_ItemTypeID FOREIGN KEY REFERENCES ItemTypes (ItemTypeID)
)

CREATE TABLE Customers (
	CustomerID INT PRIMARY KEY,
	[Name] NVARCHAR(255) NOT NULL,
	Birthday DATE NOT NULL,
	CityID INT CONSTRAINT FK_CityID FOREIGN KEY REFERENCES Cities (CityID)
)

CREATE TABLE Orders (
	OrderID INT PRIMARY KEY,
	CustomerID INT CONSTRAINT FK_CustomerID FOREIGN KEY REFERENCES Customers (CustomerID)
)

CREATE TABLE OrderItems (
	OrderID INT CONSTRAINT FK_OrderID FOREIGN KEY REFERENCES Orders (OrderID),
	ItemID INT CONSTRAINT FK_ItemID FOREIGN KEY REFERENCES Items (ItemID),
	PRIMARY KEY (OrderID, ItemID)
)